-- ALTERACAO DA TABELA DE ALUNO, PARA ACRESCIMO DO TAMANHO DOS CAMPOS DE DATA, PARA POSSIBILITAR A INCLUSAO DE VÁRIOS 
-- TELEFONES PARA UM MESMO CLIENTE.
ALTER TABLE aluno MODIFY tel_fixo varchar(100);
ALTER TABLE aluno MODIFY tel_celular varchar(100);
ALTER TABLE aluno MODIFY tel_ref varchar(100);