login:
  path: /login
  defaults: { _controller: 'Crossfit\Controllers\LoginController::login' }
  methods:  [POST]
logout:
  path: /logout
  defaults: { _controller: 'Crossfit\Controllers\LoginController::logout' }
  methods:  [POST]