# Rotas para o controller de LOGIN
login:
  path: /login
  defaults: { _controller: 'Crossfit\Controllers\LoginController::login' }
  methods:  [POST]

logout:
  path: /logout
  defaults: { _controller: 'Crossfit\Controllers\LoginController::logout' }
  methods:  [POST]

# Rotas para o controller de DASHBOARD
dashboard:
  path: /dashboard
  defaults: { _controller: 'Crossfit\Controllers\DashboardController::carregaDashboard' }
  methods:  [GET]

# Rotas para o controller de PLANO
plano:
  path: /plano
  defaults: {_controller : 'Crossfit\Controllers\PlanoController::carregaPlano' }
  methods: [GET]
cadPlano:
  path: /plano/{id_plano}
  defaults: {_controller : 'Crossfit\Controllers\PlanoController::carregaCadPlano' }
  methods: [GET]
novoPlano:
  path: /plano
  defaults: {_controller : 'Crossfit\Controllers\PlanoController::salvaPlano' }
  methods: [POST]
atualizaPlano:
  path: /plano/{id_plano}
  defaults: {_controller : 'Crossfit\Controllers\PlanoController::atualizaPlano' }
  methods: [POST]
removePlano:
  path: /plano/{id_plano}
  defaults: {_controller : 'Crossfit\Controllers\PlanoController::removePlano' }
  methods: [DELETE]

# Rotas para o controller de DESCONTO

desconto:
  path: /desconto
  defaults: {_controller : 'Crossfit\Controllers\DescontoController::carregaDesconto' }
  methods: [GET]
cadDesconto:
  path: /desconto/{id_desconto}
  defaults: {_controller : 'Crossfit\Controllers\DescontoController::carregaCadDesconto' }
  methods: [GET]
novoDesconto:
  path: /desconto
  defaults: {_controller : 'Crossfit\Controllers\DescontoController::salvaDesconto' }
  methods: [POST]
atualizaDesconto:
  path: /desconto/{id_desconto}
  defaults: {_controller : 'Crossfit\Controllers\DescontoController::atualizaDesconto' }
  methods: [POST]
removeDesconto:
  path: /desconto/{id_desconto}
  defaults: {_controller : 'Crossfit\Controllers\DescontoController::removeDesconto' }
  methods: [DELETE]

# Rotas para o controller de ESTACIONAMENTO

estacionamento:
  path: /estacionamento
  defaults: {_controller : 'Crossfit\Controllers\EstacionamentoController::carregaEstacionamento' }
  methods: [GET]
cadEstacionamento:
  path: /estacionamento/{id_estacionamento}
  defaults: {_controller : 'Crossfit\Controllers\EstacionamentoController::carregaCadEstacionamento' }
  methods: [GET]
novoEstacionamento:
  path: /estacionamento
  defaults: {_controller : 'Crossfit\Controllers\EstacionamentoController::salvaEstacionamento' }
  methods: [POST]
atualizaEstacionamento:
  path: /estacionamento/{id_estacionamento}
  defaults: {_controller : 'Crossfit\Controllers\EstacionamentoController::atualizaEstacionamento' }
  methods: [POST]
removeEstacionamento:
  path: /estacionamento/{id_estacionamento}
  defaults: {_controller : 'Crossfit\Controllers\EstacionamentoController::removeEstacionamento' }
  methods: [DELETE]