# Rotas para o controller de LOGIN
login:
  path: /login
  defaults: { _controller: 'Crossfit\Controllers\LoginController::login' }
  methods:  [POST]

logout:
  path: /logout
  defaults: { _controller: 'Crossfit\Controllers\LoginController::logout' }
  methods:  [POST]

# Rotas para o controller de DASHBOARD
dashboard:
  path: /dashboard
  defaults: { _controller: 'Crossfit\Controllers\DashboardController::carregaDashboard' }
  methods:  [GET]

# Rotas para o controller de PLANO
plano:
  path: /plano
  defaults: {_controller : 'Crossfit\Controllers\PlanoController::carregaPlano' }
  methods: [GET]
cadPlano:
  path: /plano/{id_plano}
  defaults: {_controller : 'Crossfit\Controllers\PlanoController::carregaCadPlano' }
  methods: [GET]
novoPlano:
  path: /plano
  defaults: {_controller : 'Crossfit\Controllers\PlanoController::salvaPlano' }
  methods: [POST]
atualizaPlano:
  path: /plano/{id_plano}
  defaults: {_controller : 'Crossfit\Controllers\PlanoController::atualizaPlano' }
  methods: [POST]
removePlano:
  path: /plano/{id_plano}
  defaults: {_controller : 'Crossfit\Controllers\PlanoController::removePlano' }
  methods: [DELETE]

  # Rotas para o controller de Formas de Pagamento
formapagamento:
  path: /formapagamento
  defaults: {_controller : 'Crossfit\Controllers\FormaPagamentoController::carregaFormaPagamento' }
  methods: [GET]
cadFormaPagamento:
  path: /formapagamento/{id_forma_pagamento}
  defaults: {_controller : 'Crossfit\Controllers\FormaPagamentoController::carregaCadFormaPagamento' }
  methods: [GET]
novoFormaPagamento:
  path: /formapagamento
  defaults: {_controller : 'Crossfit\Controllers\FormaPagamentoController::salvaFormaPagamento' }
  methods: [POST]
atualizaFormaPagamento:
  path: /formapagamento/{id_forma_pagamento}
  defaults: {_controller : 'Crossfit\Controllers\FormaPagamentoController::atualizaFormaPagamento' }
  methods: [POST]
removeFormaPagamento:
  path: /formapagamento/{id_forma_pagamento}
  defaults: {_controller : 'Crossfit\Controllers\FormaPagamentoController::removeFormaPagamento' }
  methods: [DELETE]

# Rotas para o controller de Aula Experimental
aulaexp:
  path: /aulaexp
  defaults: {_controller : 'Crossfit\Controllers\AulaExpController::carregaAulaExp' }
  methods: [GET]
cadAulaExp:
  path: /aulaexp/{id_aulaexp}
  defaults: {_controller : 'Crossfit\Controllers\AulaExpController::carregaCadAulaExp' }
  methods: [GET]
novoAulaExp:
  path: /aulaexp
  defaults: {_controller : 'Crossfit\Controllers\AulaExpController::salvaAulaExp' }
  methods: [POST]
atualizaAulaExp:
  path: /aulaexp/{id_aulaexp}
  defaults: {_controller : 'Crossfit\Controllers\AulaExpController::atualizaAulaExp' }
  methods: [POST]
removeAulaExp:
  path: /aulaexp/{id_aulaexp}
  defaults: {_controller : 'Crossfit\Controllers\AulaExpController::removeAulaExp' }
  methods: [DELETE]